Часть 1
1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:
а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;
оба произведения не определены
б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;
АВ определена, размерность 5, ВА не определена
в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;
АВ определена, размерность 3, ВА определена, размерность 8
г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .
Оба произведения определены, размерности 4

2. Найти сумму и произведение матриц  𝐴=(13−20)  и  𝐵=(40−15). 

In [15]:
import numpy as np
import scipy.linalg

In [10]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'Сумма матриц АВ\n{a + b}')
print(f'Произведение матриц АВ\n{a @ b}')
print(f'Произведение матриц BA\n{b @ a}')

Сумма матриц АВ
[[ 5 -3]
 [ 3  5]]
Произведение матриц АВ
[[  4 -11]
 [ 12  -3]]
Произведение матриц BA
[[ 1 -8]
 [15  0]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3𝐴−2𝐵+4𝐶  для матриц  𝐴=(137−6) ,  𝐵=(025−1) ,  𝐶=(21−41). 

In [11]:
a_1 = np.array([[1, 7], [3, -6]])
b_1 = np.array([[0, 5], [2, -1]])
c_1 = np.array([[2, -4], [1, 1]])
d_1 = 3 * a_1 - 2 * b_1 + 4 * c_1
d_1

array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица  𝐴=⎛⎝⎜⎜4521−23⎞⎠⎟⎟ . Вычислить  𝐴𝐴𝑇  и  𝐴𝑇𝐴 .

In [14]:
a_2 = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Произведение матриц АAT\n{a_2 @ a_2.T}')
print(f'Произведение матриц АTA\n{a_2.T @ a_2}')

Произведение матриц АAT
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение матриц АTA
[[45  0]
 [ 0 14]]


5. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [293]:
def trans (a, b):
    stringa = len(a)
    stringb = len(b)
    columna = 0
    columnb = 0
    str_lengtha = []
    str_lengthb = []
    for i in a:
        columna = len(i)
        str_lengtha.append(columna) 
    for k in b:
        columnb = len(k)
        str_lengthb.append(columnb)
    for j in range(0, stringa-1):
        if str_lengtha[j] != str_lengtha[j+1]:
            print('Первая матрица не прямоугольная')
    for m in range(0, stringb-1):
        if str_lengthb[m] != str_lengthb[m+1]:
            print(str_lengthb)
            print('Вторая матрица не прямоугольная')
    if columna != stringb:
        print("количество столбцов первой матрицы не совпадает с количеством строк второй")
    b_tr = []
    for l in range(0, columnb):
        b_tr_str = []
        for n in b:
            b_tr_str.append(n[l])
        b_tr.append(b_tr_str)
    c = []
    for r in a:
        matr_unit = []
        for s in b_tr:
            unit = 0
            sum_unit = 0
            for f in range(0, columna):
                unit = r[f] * s[f]
                sum_unit = sum_unit + unit
            matr_unit.append(sum_unit)
        c.append(matr_unit)
    return c

In [298]:
x = ([[1, 2, 3], [2, 3, 4], [5, 7, 2]])
y = ([[2, 3, 7], [4, 5, 8], [2, 3, 2]])
x_1 = np.array([[1, 2, 3], [2, 3, 4], [5, 7, 2]])
y_1 = np.array([[2, 3, 7], [4, 5, 8], [2, 3, 2]])
g = trans(x, y)
d = x_1.dot(y_1)
print(d)
g

[[16 22 29]
 [24 33 46]
 [42 56 95]]


[[16, 22, 29], [24, 33, 46], [42, 56, 95]]

Часть 2.
1. Вычислить определитель:
a)
∣∣∣𝑠𝑖𝑛𝑥𝑐𝑜𝑠𝑥−𝑐𝑜𝑠𝑥𝑠𝑖𝑛𝑥∣∣∣; 
sin^2x + cos^2x = 1
б)
∣∣∣∣∣400250319∣∣∣∣∣; 
4 * 5 * 9 = 180
в)
∣∣∣∣∣147258369∣∣∣∣∣. 
0

In [17]:
a_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
defa3 = np.linalg.det(a_3)
defa3

-9.51619735392994e-16

2. Определитель матрицы  𝐴  равен  4 . Найти:
а)  𝑑𝑒𝑡(𝐴^2) ;
16
б)  𝑑𝑒𝑡(𝐴𝑇) ;
4
в)  𝑑𝑒𝑡(2𝐴) .
= 8n, где n - порядок матрицы

3. Доказать, что матрица
⎛⎝⎜⎜−24−37−147−3613⎞⎠⎟⎟ 
вырожденная

In [18]:
a_4 = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
defa4 = np.linalg.det(a_4)
defa4

0.0

4. Найти ранг матрицы:
а)  ⎛⎝⎜⎜112213314⎞⎠⎟⎟; 
ранг 2, тк третья строка - сумма первых
б)  ⎛⎝⎜⎜⎜⎜0002000322451236⎞⎠⎟⎟⎟⎟. 
ранг 3 так как третья стока - сумма первых двух

In [23]:
a_5 = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
a_6 = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
ranka5 = np.linalg.matrix_rank(a_5)
ranka6 = np.linalg.matrix_rank(a_6)
ranka6

3