1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей 𝐴=(−12−66). 

In [1]:
import numpy as np

In [6]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(a)
print(w)
print(v)

[[-1 -6]
 [ 2  6]]
[2. 3.]
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


(-1 - lambda)(6 - lambda) + 12 = 0
(-x - 1)(-x + 6) + 12 = 0
x^2 + x - 6x - 6 + 12 = 0 => x^2 - 5x +6 = 0, корни 2 и 3 => lambda = 2 и 3
lambda = 2:
-1 x1 - 6 x2 = 2 x1 => -3 x1 - 6 x2 = 0 => x1 = - 2 x2
2 x1 + 6 x2 = 2 x2 => x2 = - 0.5 x1
пусть x2 = 1
собственные вектора = [-2, 1]
lambda = 3:
-1 x1 - 6 x2 = 3 x1 => -4 x1 - 6 x2 = 0 => x1 = - 1,5 x2
2 x1 + 6 x2 = 3 x2 => x2 = - 2/3 x1
пусть x2 = 1
собственные вектора = [-1,5 , 1]

2. Дан оператор поворота на 180 градусов, задаваемый матрицей
𝐴=(−100−1). 
Показать, что любой вектор является для него собственным.
при развороте на 180 градусов мы получаем коллинеарные вектора с отрицательным знаком, что соответствует определению собственного вектора (изменяет длину оператора, но не направление)

3. Пусть линейный оператор задан матрицей
𝐴=(1−113). 
Установить, является ли вектор  𝑥=(1,1)  собственным вектором этого линейного оператора.

In [3]:
b = np.array([[1, 1], [-1, 3]])
b

array([[ 1,  1],
       [-1,  3]])

1 + 1 = lambda => lambda = 2
-1 + 3 = lambda => lambda = 2
является собственным

4. Пусть линейный оператор задан матрицей
𝐴=⎛⎝⎜⎜030300003⎞⎠⎟⎟. 
Установить, является ли вектор  𝑥=(3,−3,−4)  собственным вектором этого линейного оператора.

In [6]:
c = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
d = np.array([[3], [-3], [-4]])
print(c)
print(d)

[[0 3 0]
 [3 0 0]
 [0 0 3]]
[[ 3]
 [-3]
 [-4]]


-9 = 3 lambda => lambda = -3
9 = -3 lambda => lambda = -3
-12 = -4 lambda => lambda = 3
не является собственным