Часть 1
1. Решить систему уравнений методом Гаусса:
⎧⎩⎨⎪⎪𝑥1+𝑥2−𝑥3−2𝑥4=0,2𝑥1+𝑥2−𝑥3+𝑥4=−2,𝑥1+𝑥2−3𝑥3+𝑥4=4. 

In [1]:
import numpy as np
import numpy.linalg
import scipy.linalg

In [23]:
a_1 = np.array([1, 1, -1, -2, 0])
a_2 = np.array([2, 1, -1, 1, -2])
a_3 = np.array([1, 1, -3, 1, 4])
a = np.array([a_1, a_2, a_3])
a1 = np.array([a_1, a_2 - 2 * a_1, a_3 - a_1])
print(a)
print(a1)

[[ 1  1 -1 -2  0]
 [ 2  1 -1  1 -2]
 [ 1  1 -3  1  4]]
[[ 1  1 -1 -2  0]
 [ 0 -1  1  5 -2]
 [ 0  0 -2  3  4]]


x4 = c4 => -2 x3 = 4 - 3 c4 => x3 = 1.5 c4 - 4
-x2 + 1.5 c4 - 4 + 5 c4 = -2 => x2 = 6.5 c4 -2
x1 + 6.5 c4 - 2 - 1.5 c4 + 4 - 2 c4 = 0 => x1 = -3c4 - 2
при c4 = 0, x1 = -2, x2 = -2, x3 = -4

2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:
а)  ⎧⎩⎨⎪⎪3𝑥1−𝑥2+𝑥3=4,2𝑥1−5𝑥2−3𝑥3=−17,𝑥1+𝑥2−𝑥3=0; 
б)  ⎧⎩⎨⎪⎪2𝑥1−4𝑥2+6𝑥3=1,𝑥1−2𝑥2+3𝑥3=−2,3𝑥1−6𝑥2+9𝑥3=5; 
в)  {𝑥1+2𝑥2+5𝑥3=4,3𝑥1+𝑥2−8𝑥3=−2. 

In [25]:
b1_1 = np.linalg.matrix_rank(np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]]))
b1_2 = np.linalg.matrix_rank(np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]]))
print(b1_1)
print(b1_2)
# ранги совпадают между собой и с количеством переменных, матрицы совместны, одно решение

3
3


In [26]:
b2_1 = np.linalg.matrix_rank(np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]]))
b2_2 = np.linalg.matrix_rank(np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]]))
print(b2_1)
print(b2_2)
# ранг расширенной матрицы выше, чем основной, система не имеет решений

1
2


In [27]:
b3_1 = np.linalg.matrix_rank(np.array([[1, 2, 5], [3, 1, -8]]))
b3_2 = np.linalg.matrix_rank(np.array([[1, 2, 5, 4], [3, 1, -8, -2]]))
print(b3_1)
print(b3_2)
# ранги совпадают между собой но меньше количества переменных, матрицы совместны, решений бесконечно много

2
2


3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей
𝐴̃=⎛⎝⎜⎜⎜⎜10003500−20304102∣∣∣∣∣∣∣3241⎞⎠⎟⎟⎟⎟. 

In [31]:
c1_1 = np.linalg.matrix_rank(np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]]))
c1_2 = np.linalg.matrix_rank(np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4],[0, 0, 0, 2, 1]]))
print(c1_1)
print(c1_2)
# ранги совпадают между собой и с количеством переменных, матрицы совместны, одно решение

4
4


4. Дана система линейных уравнений, заданная расширенной матрицей
𝐴̃=⎛⎝⎜⎜147258369∣∣∣∣∣𝑎𝑏𝑐⎞⎠⎟⎟. 
Найти соотношение между параметрами  𝑎 ,  𝑏  и  𝑐 , при которых система является несовместной.

In [37]:
d_1 = np.array([1, 2, 3])
d_2 = np.array([4, 5, 6])
d_3 = np.array([7, 8, 9])
d_4 = d_2 - 4 * d_1
d_5 = d_3 - 7 * d_1
d_6 = d_5 - 2 * d_4
d = np.array([d_1, d_2, d_3])
d1 = np.array([d_1, d_4, d_5])
d2 = np.array([d_1, d_4, d_6])
print(d)
print(d1)
print(d2)
# система является несовместной при с !=0

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1   2   3]
 [  0  -3  -6]
 [  0  -6 -12]]
[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]


Часть 2
1. Решить систему уравнений методом Крамера:
а)  {𝑥1−2𝑥2=1 3𝑥1−4𝑥2=7 
б)  ⎧⎩⎨⎪⎪2𝑥1−𝑥2+5𝑥3=10 𝑥1+𝑥2−3𝑥3=−2 2𝑥1+4𝑥2+𝑥3=1 

In [45]:
det_fa = np.linalg.det(np.array([[1, -2], [3, -4]]))
det_fa_1 = np.linalg.det(np.array([[1, -2], [7, -4]]))
det_fa_2 = np.linalg.det(np.array([[1, 1], [3, 7]]))
print(det_fa)
print(det_fa_1)
print(det_fa_2)
# x1 = 5, x2 = 2

2.0000000000000004
9.999999999999998
4.0


In [46]:
det_fb = np.linalg.det(np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]]))
det_fb_1 = np.linalg.det(np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]]))
det_fb_2 = np.linalg.det(np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]]))
det_fb_3 = np.linalg.det(np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]]))
print(det_fb)
print(det_fb_1)
print(det_fb_2)
print(det_fb_3)
# x1 = 2, x2 = -1, x3 = 1

42.99999999999998
86.00000000000004
-43.000000000000014
42.99999999999998


In [ ]:
2*. Найти  𝐿 -матрицу  𝐿𝑈 -разложения для матрицы коэффициентов:
а)
⎛⎝⎜⎜123292641230⎞⎠⎟⎟ 
б)
⎛⎝⎜⎜⎜⎜1234151822282953491833⎞⎠⎟⎟⎟⎟ 

In [53]:
g_1 = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
g_1

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

In [52]:
g1_r = scipy.linalg.lu(g_1)
g1_r
# Вторая матрица и есть L

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.66666667, 1.        , 0.        ],
        [0.33333333, 0.8       , 1.        ]]),
 array([[ 3.        , 26.        , 30.        ],
        [ 0.        , -8.33333333, -8.        ],
        [ 0.        ,  0.        ,  0.4       ]]))

In [54]:
g_2 = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
g_2

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

In [55]:
g2_r = scipy.linalg.lu(g_2)
g2_r
# Вторая матрица и есть L

(array([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.5       ,  1.        ,  0.        ,  0.        ],
        [ 0.75      , -0.25      ,  1.        ,  0.        ],
        [ 0.25      ,  0.75      , -0.17073171,  1.        ]]),
 array([[  4.        ,  22.        ,  53.        ,  33.        ],
        [  0.        ,  -6.        , -18.5       ,  -7.5       ],
        [  0.        ,   0.        , -15.375     ,  -8.625     ],
        [  0.        ,   0.        ,   0.        ,  -0.09756098]]))

In [14]:
h_1 = np.array([[11, 7, 5],[9, 8, 4], [2, 1, 3]])
h_2 = [-6, -5, 1]
h_1

array([[11,  7,  5],
       [ 9,  8,  4],
       [ 2,  1,  3]])

In [15]:
h1_r = scipy.linalg.lu(h_1)
h1_r

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [ 0.81818182,  1.        ,  0.        ],
        [ 0.18181818, -0.12      ,  1.        ]]),
 array([[11.        ,  7.        ,  5.        ],
        [ 0.        ,  2.27272727, -0.09090909],
        [ 0.        ,  0.        ,  2.08      ]]))

y1 = -6
9/11 y1 + y2 = -6 => y2 = -1/11
2/11 * -6 - 0.12 * -1/11 + y3 = 1 => y3 = 2.08
2.08 x3 = 2.08 => x3 = 1
2 3/11 x2 - 1/11 * 1 = -1/11 => x2 = 0
11 x1 + 7 * 0 + 5 * 1 = -6 => x1 = -1

In [33]:
y1 = -6
y2 = -5 - 0.81818182 * y1
y3 = 1 - 0.18181818 * y1 + 0.12 * y2
x3 = y3/2.08
x2 = -0.09090909 - y2
x1 = (-6 - 5 * x3) / 11
print(y1, y2, y3)
print(x1, x2, x3)

-6 -0.09090908000000031 2.0799999903999997
-0.9999999979020978 -9.99999968942511e-09 0.9999999953846153


In [53]:
i = np.array([[81, -45, 45],[-45, 50, -15], [45, -15, 38]])
i_s = np.array([531, -460, 193])
i_r = scipy.linalg.cholesky(i)
i_chf = scipy.linalg.cho_factor(i)
i_r_t = i_r.T
i_chf

(array([[  9.,  -5.,   5.],
        [-45.,   5.,   2.],
        [ 45., -15.,   3.]]),
 False)

In [54]:
i_r_s = scipy.linalg.cho_solve(i_chf, i_s)
i_r_s

array([ 6., -5., -4.])